### ISSUE TITLE
Missing tag information

### ISSUE THREAD

**Issue by urutva** [ARMmbed/sal-nanostack-driver-k64f-eth#1]
Yotta generates the following `warning: Github repository "ARMmbed/sal-nanostack-driver-k64f-eth" has no tagged versions, default branch will be used` as there are no tags available on this module. Yotta generates this warning  as an indication that a known version cannot be downloaded for this module instead a default branch is used.

module.json:
`"sal-nanostack-driver-k64f-eth": "ARMmbed/sal-nanostack-driver-k64f-eth"`

**Comment by hasnainvirk** [comment]
Released. So the tag is in its place.
