### ISSUE TITLE
After startup without connection, get an error "TX buf descriptors full. Can't queue packet"

### ISSUE THREAD

**Issue by EricRemmerswaal** [ARMmbed/sal-nanostack-driver-k64f-eth#13]
I have a wired setup using ipv6. 
When starting the mbed network stack without ethernet connected I get an "[ERR ][ethDrv]: TX buf descriptors full. Can't queue packet" error. After re-connecting the ethernet this error remains. No recovery. After reset the error is gone.

My mbed module versions:
|_ mbed-client 1.12.4
| |_ mbed-client-c 2.7.3 yotta_modules\mbed-client-c
| | _ nanostack-libservice 3.5.3 yotta_modules\nanostack-libservice
| |_ mbed-trace 1.2.1 yotta_modules\mbed-trace
| |_ mbed-client-mbed-os 3.0.0 yotta_modules\mbed-client-mbed-os
| | |_ mbed-drivers 1.5.0 yotta_modules\mbed-drivers
| | | |_ cmsis-core 1.2.0 yotta_modules\cmsis-core
| | | | _ cmsis-core-freescale 1.1.0 yotta_modules\cmsis-core-freescale
| | | |   _ cmsis-core-k64f 1.1.0 yotta_modules\cmsis-core-k64f
| | | |_ ualloc 1.3.0 yotta_modules\ualloc
| | | | _ dlmalloc 1.1.0 yotta_modules\dlmalloc
| | | |_ minar 1.3.0 yotta_modules\minar
| | | | _ minar-platform 1.1.0 yotta_modules\minar-platform
| | | |   _ minar-platform-mbed 1.3.0 yotta_modules\minar-platform-mbed
| | | |_ core-util 1.8.0 yotta_modules\core-util
| | | |_ compiler-polyfill 1.3.0 yotta_modules\compiler-polyfill
| | | _ greentea-client 1.1.0 yotta_modules\greentea-client
| | _ sockets 1.3.0 yotta_modules\sockets
| |   _ sal 1.3.1 yotta_modules\sal
| |     _ sal-stack-lwip 1.4.1 yotta_modules\sal-stack-lwip
| |       |_ sal-driver-lwip-k64f-eth 1.1.0 yotta_modules\sal-driver-lwip-k64f-eth
| |       _ sal-iface-eth 1.1.0 yotta_modules\sal-iface-eth
| _ mbed-client-mbedtls 3.0.0 yotta_modules\mbed-client-mbedtls
|   _ mbedtls 2.3.0 yotta_modules\mbedtls
|_ mbed-mesh-api 2.3.0
| _ sal-iface-6lowpan 2.1.1 yotta_modules\sal-iface-6lowpan
|   _ sal-stack-nanostack 4.1.0 yotta_modules\sal-stack-nanostack
|     |_ sal-stack-nanostack-eventloop 1.1.0 yotta_modules\sal-stack-nanostack-eventloop
|     | _ mbed-6lowpan-eventloop-adaptor 1.2.4 yotta_modules\mbed-6lowpan-eventloop-adaptor
|     |_ nanostack-randlib 1.1.0 yotta_modules\nanostack-randlib
|     _ coap-service 2.2.0 yotta_modules\coap-service
|_ sal-nanostack-driver-k64f-eth 1.1.2

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2707

**Comment by hasnainvirk** [comment]
@ericremmerswaal 

Hi Eric,
Is there a particular reason that you are using an older version of of the driver and sal-stack-nanostack ?
The stable version of the driver is 2.0.0 which complies with sal-stack-nanostack 5.0.0.
Can you please update your setup and try again ?

**Comment by EricRemmerswaal** [comment]
Hi, I am working on openAIS. I do not see that we limit the version of sal-stack-nanostack to 4.1.0.
I do not get version 5.0.0 with the yotta update.

Because of API changes Devaraj (@devran01) set our "sal-nanostack-driver-k64f-eth" version to "^1.0.0". 
Building with "sal-nanostack-driver-k64f-eth" for the latest version result in errors for now.

**Comment by EricRemmerswaal** [comment]
Now running on latest modules but problem is still there.

My mbed module versions:
|_ mbed-client 1.12.7
| |_ mbed-client-c 2.7.5 yotta_modules\mbed-client-c
| | _ nanostack-libservice 3.6.0 yotta_modules\nanostack-libservice
| |_ mbed-trace 1.2.1 yotta_modules\mbed-trace
| |_ mbed-client-mbed-os 3.0.1 yotta_modules\mbed-client-mbed-os
| | |_ mbed-drivers 1.5.0 yotta_modules\mbed-drivers
| | | |_ cmsis-core 1.2.0 yotta_modules\cmsis-core
| | | | _ cmsis-core-freescale 1.1.0 yotta_modules\cmsis-core-freescale
| | | |   _ cmsis-core-k64f 1.1.0 yotta_modules\cmsis-core-k64f
| | | |_ ualloc 1.3.0 yotta_modules\ualloc
| | | | _ dlmalloc 1.1.0 yotta_modules\dlmalloc
| | | |_ minar 1.3.0 yotta_modules\minar
| | | | _ minar-platform 1.1.0 yotta_modules\minar-platform
| | | |   _ minar-platform-mbed 1.3.0 yotta_modules\minar-platform-mbed
| | | |_ core-util 1.8.0 yotta_modules\core-util
| | | |_ compiler-polyfill 1.3.0 yotta_modules\compiler-polyfill
| | | _ greentea-client 1.1.0 yotta_modules\greentea-client
| | _ sockets 1.3.0 yotta_modules\sockets
| |   _ sal 1.3.1 yotta_modules\sal
| _ mbed-client-mbedtls 3.0.1 yotta_modules\mbed-client-mbedtls
|   _ mbedtls 2.3.1 yotta_modules\mbedtls
|_ mbed-mesh-api 3.0.1
| _ sal-iface-6lowpan 2.1.1 yotta_modules\sal-iface-6lowpan
|_ sal-nanostack-driver-k64f-eth 2.0.0
|_ sal-stack-nanostack 5.0.3
| |_ sal-stack-nanostack-eventloop 1.1.0 yotta_modules\sal-stack-nanostack-eventloop
| | _ mbed-6lowpan-eventloop-adaptor 1.2.4 yotta_modules\mbed-6lowpan-eventloop-adaptor
| |_ nanostack-randlib 1.1.0 yotta_modules\nanostack-randlib
| _ coap-service 4.0.1 yotta_modules\coap-service
_ mbed-hal 1.3.0
  _ mbed-hal-freescale 1.1.0 yotta_modules\mbed-hal-freescale
    _ mbed-hal-ksdk-mcu 1.3.0 yotta_modules\mbed-hal-ksdk-mcu
      |_ uvisor-lib 2.1.2 yotta_modules\uvisor-lib
      _ mbed-hal-k64f 1.3.0 yotta_modules\mbed-hal-k64f
        _ mbed-hal-frdm-k64f 1.1.1 yotta_modules\mbed-hal-frdm-k64f

**Comment by EricRemmerswaal** [comment]
Today updated to sal-stack-nanostack@5.0.4 and sal-nanostack-driver-k64f-eth@2.0.0
Now when running with network cable attached and removed after boot-up, and re-inserted again the network communications recover. However, when booting without network cable attached and reinserted after boot-up the network communications still fails with "[ERR ][ethDrv]: TX buf descriptors full. Can't queue packet" error.

**Comment by hasnainvirk** [comment]
Hi @ericremmerswaal can you please share your module.json here with me ? And if you can a config.json too ?

**Comment by EricRemmerswaal** [comment]
My module.json

```
{
  "name": "openais-mbed-philips",
  "version": "0.1.0",
  "description": "OpenAIS Philips",
  "keywords": [
    "mbed-client"
  ],
  "author": "yogesh.pande@arm.com",
  "license": "Apache-2.0",
  "extraIncludes": [],
  "dependencies": {
    "mbed-client": "*",
    "mbed-mesh-api": "^3.0.0",
    "sal-nanostack-driver-k64f-eth": "^2.0.0",
    "sal-stack-nanostack": "^5.0.0", 
    "openais-mbed-common": "openais-eu-project/openais-mbed-common",
    "openais-mbed-vendor-interface": "*",
    "openais-mbed-vendor-philips":  "*",
    "openais-driver-push-button" :  "*"
  },
  "targetDependencies":{
    "mbed": {
        "mbed-hal": "*"
    },
    "/openais/vendor/philips": {
      "openais-mbed-vendor-philips":  "~0.1.0"
    }
  },
  "bin": "./source/"
}
```

My config.json

```
{
  "mbed-os": {
    "net": {
      "stacks": {
         "lwip": false,
         "nanostack": true
      }
    }
  },
  "debug": {},
  "coap_duplication_max_msgs_count": 3,
  "coap_max_blockwise_payload_size": 512,  
  "P2P": {
    "listen_port": 5685,
    },
  "openais": {
    "listen_port": 5683,
    "lwm2m_server_uri"     : "\"coap://aabb::30:5683\""
   },  
}
```

**Comment by hasnainvirk** [comment]
It seems I am unable to recreate the issue. I am testing with Ethernet driver version 2.0.0 and Nanostack v 5.0.4. Can you talk to me on skype ?

**Comment by EricRemmerswaal** [comment]
I am able to recreate the problem by power-up (NOT reset) the frdm-k64 board without network cable attached. After system boot-up the "[ERR ][ethDrv]: TX buf descriptors full. Can't queue packet." is reported. Plug-in network cable, error continues and no network communications happen.

**Comment by hasnainvirk** [comment]
I think you are not handling backhaul_interface_ready callbacks and stack events in your application. Can we use some other channel to look and fix your code ?

**Comment by EricRemmerswaal** [comment]
backhaul_interface_ready callbacks and  stack events sounds like nanostack implementation.
If that is the case, I do not have access to the nanostack sources, only linking the lib.

**Comment by hasnainvirk** [comment]
No. They are application callbacks. Application needs to handle those.

**Comment by EricRemmerswaal** [comment]
Fixed the problem after a screen-share session:
Was not a driver problem but incorrect initialization in end_node_tasklet@application_event, causing a memory-leak.

Tnx for spotting the problem.
