### ISSUE TITLE
Wrong include guard

### ISSUE THREAD

**Issue by stevew817** [ARMmbed/sal-nanostack-driver-k64f-eth#17]
The K64F ethernet driver uses the same include guard as the Atmel RF driver... Yikes.
https://github.com/ARMmbed/sal-nanostack-driver-k64f-eth/blob/dafa84646b48287273c57d0f677ccc39e33c4cb3/sal-nanostack-driver-k64f-eth/NanostackEthernetPhyK64F.h#L17

**Comment by hasnainvirk** [comment]
@SeppoTakalo :)

**Comment by hasnainvirk** [comment]
Fixed in https://github.com/ARMmbed/sal-nanostack-driver-k64f-eth/commit/cae5830bfdfc2f77cbc4c7c8d7d5c501e1c27dc1
