### ISSUE TITLE
ping request fails with an error "TX buf descriptors full. Can't queue packet."

### ISSUE THREAD

**Issue by urutva** [ARMmbed/sal-nanostack-driver-k64f-eth#9]
With thread border router, pinging devices connected to external network with payload size higher than 1402 bytes fails with an error "[ERR ][ethDrv]: TX buf descriptors full. Can't queue packet.". However, ping request with payload size 1402 or lower works fine. It seems like synchronization issue between nanostack and ethernet driver in case of fragmentation.

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2550

**Comment by hasnainvirk** [comment]
Yes that is supposed to happen. Too many fragments. What is wrong with it ? What is the catch here ? Your border router should not hang here. If it does, that's not Ethernet Issue. I tested it with 6LoWPAN. Border router gets back to Normal operation once buffers are cleared. Also, I think you need to fetch the updated driver as this trace is not displayed anymore. It was confusing people, as it is actually not an error. It just tells you that all buffers are full, too fast and too many packets in too short time(nanostack is limited by radio capacity)

**Comment by urutva** [comment]
This issue is related to Eth Tx and NOT Rx. The thread application is using the latest driver and still issue exists. In case of fragmentation (ping request FROM border router with payload size higher than 1402 bytes) it seems like nanostack pushes fragments at faster rate than the Ethernet driver can handle resulting in the error "[ERR ][ethDrv]: TX buf descriptors full. Can't queue packet.".

**Comment by hasnainvirk** [comment]
https://github.com/ARMmbed/sal-nanostack-driver-k64f-eth/pull/11/commits/c9ace0e878913dae8d24894228513270fd0e34f3
